services:
  redis:
    image: redis:7.2
    container_name: circa_redis
    ports:
      - "6377:6379"
    volumes:
      - redis_data:/data
    networks:
      - circa

volumes:
  redis_data:

networks:
  circa:
    driver: bridge
